name: time_sheet
version: 0.0.1
description: time sheets component
author: yamal lng
homepage: http://yamallng.ru/

dependencies:
    angular2: ^2.2.0
    browser: ^0.10.0
    dart_to_js_script_rewriter: ^1.0.2
    http: ^0.11.1
    intl: any
    reflectable: ^1.0.2
    aside:
      git: http://cm-ylng-msk-04/git/aside.frontend.git
    alert:
      git: http://cm-ylng-msk-04/git/alert.frontend.git
    logger:
      git: http://cm-ylng-msk-04/git/logger.frontend.git
    config:
      git: http://cm-ylng-msk-04/git/config.frontend.git
    converters:
      git: http://cm-ylng-msk-04/git/converters.frontend.git
dev_dependencies:
    test: ^0.12.18
    yaml: ^2.1.12
    master_layout:
      git: http://cm-ylng-msk-04/git/master_layout.frontend.git

transformers:
    - angular2:
        platform_directives:
          - package:angular2/common.dart#COMMON_DIRECTIVES
        platform_pipes:
          - package:angular2/common.dart#COMMON_PIPES
        entry_points: web/main.dart
        resolved_identifiers:
            BrowserClient: 'package:http/browser_client.dart'
            Client: 'package:http/http.dart'
    - reflectable:
        entry_points:
          - web/main.dart
        formatted: true
    - dart_to_js_script_rewriter
    - $dart2js:
        commandLineOptions:
            - --trust-type-annotations
            - --trust-primitives
            - --show-package-warnings
            - --enable-experimental-mirrors